using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ShibaCompiler
{
    /// <summary>
    /// コンパイルエラーの種類。基本はABC順。
    /// </summary>
    enum CompileErrorKind
    {
        NONE, // エラー無し

        // SystemError
        SYSTEM_ERROR_START = 100,

        SYSTEM_CANT_OPEN_SRC_FILE,

        // LexerError
        LEXER_ERROR_START = 1000,

        LEXER_UNSUPPORTED_CHAR,
        LEXER_UNTERM_BLOCK_COMMENT,
        LEXER_UNTERM_CHAR_CONSTANT,
        LEXER_UNTERM_STRING_CONSTANT,
        LEXER_UNTERM_UNDEFINED_ESCAPE_SEQUENCE,

        // ParserError
        PARSER_ERROR_START = 2000,

        PARSER_ALREADY_ASSIGNED_ATTRIBUTE_ABSTRACT,
        PARSER_ALREADY_ASSIGNED_ATTRIBUTE_CONST,
        PARSER_ALREADY_ASSIGNED_ATTRIBUTE_IN,
        PARSER_ALREADY_ASSIGNED_ATTRIBUTE_OVERRIDE,
        PARSER_ALREADY_ASSIGNED_ATTRIBUTE_READONLY,
        PARSER_ALREADY_ASSIGNED_ATTRIBUTE_REF,
        PARSER_ALREADY_ASSIGNED_ATTRIBUTE_STATIC,
        PARSER_ALREADY_ASSIGNED_TYPE_PROTECTION,
        PARSER_ALREADY_ASSIGNED_TYPE_KIND,
        PARSER_COLON_EXPECTED,
        PARSER_COMMA_EXPECTED,
        PARSER_DOT_EXPECTED,
        PARSER_IDENTIFIER_EXPECTED,
        PARSER_ILLEGAL_ATTRIBUTE_FOR_MEMBER_VARIABLE_DECL,
        PARSER_ILLEGAL_ATTRIBUTE_FOR_MEMBER_FUNCTION_DECL,
        PARSER_ILLEGAL_ATTRIBUTE_FOR_STATIC_TYPE_DEF,
        PARSER_ILLEGAL_MEMBER_SYNTAX,
        PARSER_INTERFACE_CANT_HAVE_NONSTATIC_MEMBER_VARIABLE,
        PARSER_KEYWORD_MODULE_EXPECTED,
        PARSER_KEYWORD_TYPE_EXPECTED,
        PARSER_KEYWORD_WHILE_EXPECTED,
        PARSER_LBRACKET_EXPECTED,
        PARSER_LCURLY_EXPECTED,
        PARSER_LPAREN_EXPECTED,
        PARSER_ONLY_CLASS_OR_INTERFACE_CAN_IMPLEMENT_INTERFACE,
        PARSER_ONLY_CLASS_TYPE_CAN_OVERRIDE_ATTRIBUTE_MEMBER,
        PARSER_ONLY_INTERFACE_TYPE_CAN_ABSTRACT_ATTRIBUTE_MEMBER,
        PARSER_PROTECTION_CANT_USE_PRIVATE_IN_PROTOTYPE_MODULE,
        PARSER_RBRACKET_EXPECTED,
        PARSER_RCURLY_EXPECTED,
        PARSER_RPAREN_EXPECTED,
        PARSER_SEMICOLON_EXPECTED,
        PARSER_TYPE_PROTECTION_MUST_BE_PUBLIC,
        PARSER_UTILITY_CANT_HAVE_NONSTATIC_MEMBER_VARIABLE,

        // SymbolTreeError
        STREE_ERROR_START = 3000,

        STREE_CANT_IMPLICIT_CAST_TYPEA_TO_TYPEB,
        STREE_EXPRESSION_EXPECTED,
        STREE_FUNCTION_SYMBOL_EXPECTED,
        STREE_INVALID_BREAK,
        STREE_INVALID_CONTINUE,
        STREE_NODE_NAME_IS_ALREADY_EXIST,
        STREE_NODE_NAME_IS_ALREADY_EXIST_AS_NOT_NAMESPACE,
        STREE_NOT_DECLARATION_IDENTIFIER,
        STREE_NOT_SUPPORTED_EXPRESSION,
        STREE_NOT_SUPPORTED_TYPENAME,
        STREE_SEMICOLON_EXPECTED,
    }
}
