// -*- C++ -*- generated by wxGlade 0.5 on Wed Sep 19 23:11:56 2007 from C:\Documents and Settings\akiharu\My Documents\projects\glpicviewer\data\wxGlade\MainWindow.wxg

#include "GUIMainWindow.h"


GUIMainWindow::GUIMainWindow(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: GUIMainWindow::GUIMainWindow
    menubar_ = new wxMenuBar();
    SetMenuBar(menubar_);
    wxMenu* wxglade_tmp_menu_1 = new wxMenu();
    wxglade_tmp_menu_1->Append(wxID_ANY, wxT("Open"), wxEmptyString, wxITEM_NORMAL);
    wxglade_tmp_menu_1->AppendSeparator();
    wxglade_tmp_menu_1->Append(wxID_ANY, wxT("Exit"), wxEmptyString, wxITEM_NORMAL);
    menubar_->Append(wxglade_tmp_menu_1, wxT("File"));

    set_properties();
    do_layout();
    // end wxGlade
}


void GUIMainWindow::set_properties()
{
    // begin wxGlade: GUIMainWindow::set_properties
    SetTitle(wxT("GLPicViewer"));
    // end wxGlade
}


void GUIMainWindow::do_layout()
{
    // begin wxGlade: GUIMainWindow::do_layout
    wxBoxSizer* sizer_ = new wxBoxSizer(wxVERTICAL);
    SetSizer(sizer_);
    sizer_->Fit(this);
    Layout();
    // end wxGlade
}

